################################################################################
#
# Top level Makefile for Toddler IA32
#
# Use Makefile.config to override any of the following variables
#
################################################################################


# Uncomment if you want to build IA32 Toddler on an AMD64 host.
CFLAGS	+= -m32 -O3
LDFLAGS	+= -m elf_i386

# Entry points
HALENTRY	= 0xFFF88000		# 4GB - 512KB + 32KB
KRNLENTRY	= 0xFFF01000		# 4GB - 1MB + 4KB
APPENTRY	= 0x8080000		# 128MB + 512KB
LIBCENTRY	= 0xC0001000
