################################################################################
#
# Top level Makefile for Toddler
#
# Use Makefile.config to override any of the following variables
#
################################################################################

# Target CPU architecture.
# Supported values
#   ia32
ARCH	= ia32

# The path of the project.
# Note that only absolute path should be used
PROJDIR = $(CURDIR)

# Whether to build a debug version.
#   1 = Build a debug version as well as a non-debug version [Default]
#   0 = Build a non-debug version only
DEBUG	= 1

# Treat warnings as errors
CFLAGS	+= -Wall -Wpointer-arith -Wcast-align -Wno-int-to-pointer-cast
CFLAGS	+= -Werror

#-Wno-parentheses	\
#		-Wno-char-subscripts -Wno-uninitialized		\
#		-Wno-sequence-point -Wno-missing-braces		\
#		-Wno-unused-value -Wno-overflow -Wno-int-to-pointer-cast
