################################################################################
#
# Top level Makefile for Toddler PowerPC
#
# Use Makefile.config to override any of the following variables
#
################################################################################


# Assembler, Compiler, Linker, and Flags
ASM		= powerpc-linux-gnu-as
ASMFLAGS	= $(CFLAGS)

ASMBOOT		= powerpc-linux-gnu-as
ASMBOOTFLAGS	= $(CFLAGS)

CC		= powerpc-linux-gnu-gcc
CFLAGS		+=

LD		= powerpc-linux-gnu-ld
LDFLAGS		+=

DASM		=
DASMFLAGS	=

GENBIN		= powerpc-linux-gnu-objcopy
GENBINFLAGS	= -O binary

GENMAP		= powerpc-linux-gnu-objcopy
GENMAPFLAGS	= --only-keep-debug

STRIP		= powerpc-linux-gnu-strip
STRIPFLAGS	=


# Entry points
HALENTRY	= 0xFFF88000		# 4GB - 512KB + 32KB
KRNLENTRY	= 0xFFF01000		# 4GB - 1MB + 4KB
APPENTRY	= 0x8080000		# 128MB + 512KB
LIBCENTRY	= 0xC0001000
