################################################################################
#                                                                              #
# Makefile for Toddler                                                         #
#                                                                              #
################################################################################

# Phony target
.PHONY: all clean

# Make all
all: all_subdir

# Make clean
clean: clean_subdir

# Include the SUBDIR template
include $(SRCDIR)/Makefile.subdir
